In [2]:
"""
Here we are looking for a trading strategy using the AAII sentiment survey results. 

We used Machine Learning to analyze data from the AAII website.

It is weekly data of the survey of its members. It asks its members how
they feel about the stock market. For each week they get a % bullish, % neutral, % bearish. 

"""
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report



%matplotlib inline

In [3]:
#Read in AAII Sentiment data from csv

csvpath = Path(f"C:/Users/costa/Desktop/byte/rice/ru-hou-fin-pt-03-2020-u-c/Project_2_dream_team/sentiment.csv",
                  index_col="date", infer_datetime_format=True, parse_dates=True)
stock_data_df = pd.read_csv(csvpath)
stock_data_df['Date'] = pd.to_datetime(stock_data_df['Date'] )
#stock_data_df.set_index('Date',inplace=True) 

#Change Monthly Close column to 'Close'
#stock_data_df.rename(columns={'SP500 Weekly Close': 'Close'},inplace=True)
#stock_data_df.drop(["Unnamed: 14"], axis=1, inplace=True)

stock_data_df.head(20)


Date  Bullish  Neutral  Bearish  Bull 8 wk mov avg  \
0         NaT      NaN      NaN      NaN                NaN   
1  1987-06-26      NaN      NaN      NaN                NaN   
2  1987-07-17      NaN      NaN      NaN                NaN   
3  1987-07-24     0.36     0.50     0.14                NaN   
4  1987-07-31     0.26     0.48     0.26                NaN   
5  1987-08-07     0.56     0.15     0.29                NaN   
6  1987-08-14     0.45     0.35     0.20                NaN   
7  1987-08-21     0.66     0.28     0.06                NaN   
8  1987-08-28     0.52     0.18     0.30                NaN   
9  1987-09-04     0.42     0.17     0.41                NaN   
10 1987-09-11     0.50     0.23     0.27               0.47   
11 1987-09-18     0.60     0.29     0.11               0.50   
12 1987-09-25     0.53     0.17     0.30               0.53   
13 1987-10-02     0.44     0.26     0.30               0.52   
14 1987-10-09     0.46     0.39     0.15               0.52   
15 1987-10-16     0.37     0.30     0.33               0.48   
16 1987-10-23     0.39     0.30     0.31               0.46   
17 1987-10-30     0.44     0.23     0.33               0.47   
18 1987-11-06     0.47     0.31     0.22               0.46   
19 1987-11-13     0.31     0.41     0.28               0.43   

    Bull 16 wk mov avg  Bear 8 wk mov avg  Bear 16 wk mov avg  \
0                  NaN                NaN                 NaN   
1                  NaN                NaN                 NaN   
2                  NaN                NaN                 NaN   
3                  NaN                NaN                 NaN   
4                  NaN                NaN                 NaN   
5                  NaN                NaN                 NaN   
6                  NaN                NaN                 NaN   
7                  NaN                NaN                 NaN   
8                  NaN                NaN                 NaN   
9                  NaN                NaN                 NaN   
10                 NaN               0.24                 NaN   
11                 NaN               0.24                 NaN   
12                 NaN               0.24                 NaN   
13                 NaN               0.24                 NaN   
14                 NaN               0.24                 NaN   
15                 NaN               0.27                 NaN   
16                 NaN               0.27                 NaN   
17                 NaN               0.26                 NaN   
18                0.29               0.26                0.25   
19                0.28               0.28                0.26   

    Neutral 8 wk mov avg  Neutral 16 wk mov avg  Bull-Bear Spread   Close  \
0                    NaN                    NaN               NaN     NaN   
1                    NaN                    NaN               NaN     NaN   
2                    NaN                    NaN               NaN  314.59   
3                    NaN                    NaN              0.22  309.27   
4                    NaN                    NaN              0.00  318.66   
5                    NaN                    NaN              0.27  323.00   
6                    NaN                    NaN              0.25  333.99   
7                    NaN                    NaN              0.60  335.90   
8                    NaN                    NaN              0.22  323.04   
9                    NaN                    NaN              0.01  316.70   
10                  0.29                    NaN              0.23  321.98   
11                  0.27                    NaN              0.49  314.86   
12                  0.23                    NaN              0.23  320.16   
13                  0.24                    NaN              0.14  328.07   
14                  0.25                    NaN              0.31  311.07   
15                  0.25                    NaN              0.04  282.70   
16        

In [4]:
#Clean data

#Sort earliest to latest.
stock_data_df.sort_index(inplace=True, ascending=True)

# Drop nulls
stock_data_df.dropna(inplace=True)

# drop duplicates
stock_data_df.drop_duplicates(inplace=True)

#count nulls 
stock_data_df.isnull().sum()

#Create up,down,neutral signals in a new column

stock_data_df['Signal 4 wks'] = 0

stock_data_df['4 wk chg'] = (stock_data_df['Close in 4 wks']- stock_data_df['Close'])/stock_data_df['Close']

#Set signal 4 wks to UP if the market is up 3% or more, NEUTRAL if less than 3% but greater than 0%, 
# DOWN when less than zero

up_mask = (stock_data_df['4 wk chg'] > .03) 
stock_data_df.loc[up_mask, 'Signal 4 wks'] = "UP"

# if stock_data_df["Signal 4 wks"].item != 'UP':
down_mask = (stock_data_df['4 wk chg'] < 0)
stock_data_df.loc[down_mask, 'Signal 4 wks'] = "DOWN"

stock_data_df['Signal 4 wks'] = stock_data_df['Signal 4 wks'].replace([0], 'NEUTRAL')


# if stock_data_df["Signal 4 wks"].item != 'UP':
#     if stock_data_df["Signal 4 wks"].item != 'DOWN':
#         neutral_mask = (stock_data_df['4 wk chg'].item >0 and stock_data_df['4 wk chg'].item <.03)
#         stock_data_df.loc[neutral_mask,'Signal 4 wks'] = 'NEUTRAl'
        
        
# if stock_data_df["Signal 4 wks"].item != "UP":
#     if stock_data_df["Signal 4 wks"].item != "DOWN":
#         neutral_mask = (stock_data_df['4 wk chg']>0)
#         stock_data_df.loc[neutral_mask,'Signal 4 wks'] = 'NEUTRAl'
    
    
# if stock_data_df['Signal 4 wks'].item != "UP" or stock_data_df['Signal 4 wks'].item != "DOWN":
#     neutral_mask = (stock_data_df['4 wk chg'].item>0 and stock_data_df['4 wk chg'].item <.03)
#     stock_data_df.loc[neutral_mask, 'Signal 4 wks'] = "NEUTRAL"


# for index, row in stock_data_df.iterrows():
  
#     if stock_data_df['4 wk chg'].03:
#         stock_data_df['Signal 4 wks'] = 'UP'
        
#     elif stock_data_df['4 wk chg'].item !=.03:   
#         stock_data_df['Signal 4 wks'] = 'NEUTRAL'
#     else:
#         stock_data_df['Signal 4 wks'] = 'DOWN'

# target = ['Close']
stock_data_df.set_index('Date',inplace=True)
stock_data_df.head(50)



Bullish  Neutral  Bearish  Bull 8 wk mov avg  Bull 16 wk mov avg  \
Date                                                                           
1987-11-06     0.47     0.31     0.22               0.46                0.29   
1987-11-13     0.31     0.41     0.28               0.43                0.28   
1987-11-20     0.39     0.42     0.19               0.41                0.28   
1987-11-27     0.27     0.46     0.27               0.39                0.30   
1987-12-04     0.25     0.33     0.42               0.36                0.30   
1987-12-11     0.23     0.45     0.32               0.34                0.31   
1987-12-18     0.33     0.40     0.27               0.34                0.32   
1987-12-24     0.28     0.52     0.20               0.32                0.34   
1987-12-31     0.25     0.49     0.26               0.29                0.36   
1988-01-08     0.34     0.46     0.20               0.29                0.37   
1988-01-15     0.34     0.40     0.26               0.29                0.38   
1988-01-22     0.21     0.48     0.31               0.28                0.40   
1988-01-29     0.26     0.45     0.29               0.28                0.40   
1988-02-05     0.32     0.53     0.15               0.29                0.42   
1988-02-12     0.32     0.46     0.22               0.29                0.43   
1988-02-19     0.27     0.49     0.24               0.29                0.44   
1988-02-26     0.30     0.51     0.19               0.30                0.45   
1988-03-04     0.38     0.40     0.22               0.30                0.45   
1988-03-11     0.43     0.40     0.17               0.31                0.45   
1988-03-18     0.41     0.49     0.10               0.34                0.45   
1988-03-25     0.45     0.38     0.17               0.36                0.46   
1988-04-01     0.35     0.45     0.20               0.36                0.46   
1988-04-08     0.33     0.48     0.19               0.37                0.46   
1988-04-15     0.23     0.53     0.24               0.36                0.46   
1988-04-22     0.23     0.57     0.20               0.35                0.47   
1988-04-29     0.22     0.48     0.30               0.33                0.47   
1988-05-06     0.38     0.42     0.20               0.33                0.47   
1988-05-13     0.19     0.56     0.25               0.30                0.48   
1988-05-20     0.23     0.52     0.25               0.27                0.48   
1988-05-27     0.28     0.52     0.20               0.26                0.48   
1988-06-03     0.26     0.62     0.12               0.25                0.49   
1988-06-10     0.28     0.49     0.23               0.26                0.49   
1988-06-17     0.29     0.50     0.21               0.27                0.49   
1988-06-24     0.33     0.44     0.23               0.28                0.49   
1988-07-01     0.45     0.38     0.17               0.29                0.49   
1988-07-08     0.35     0.50     0.15               0.31                0.49   
1988-07-15     0.26     0.37     0.37               0.31                0.49   
1988-07-22     0.16     0.58     0.26               0.30                0.50   
1988-07-29     0.23     0.54     0.23               0.29                0.50   
1988-08-05     0.21     0.49     0.30               0.29                0.50   
1988-08-12     0.26     0.48     0.26               0.28                0.49   
1988-08-19     0.19     0.53     0.28               0.26                0.50   
1988-08-26     0.28     0.40     0.32               0.24                0.50   
1988-09-02     0.18     0.43     0.39               0.22                0.49   
1988-09-09     0.17     0.52     0.31               0.21                0.49   
1988-09-16     0.24     0.46     0.30               0.22                0.48   
1988-09-23     0.20     0.53     0.27               0.22                0.48   
1988-09-30     0.26     0.44     0.30               0.22                0.47   
1988-10-07  

In [5]:
# Create our features
from sklearn.preprocessing import LabelEncoder, StandardScaler

y = stock_data_df['Signal 4 wks']
col = ['Signal 4 wks', '4 wk chg', 'Close in 8 wks', 'Close in 4 wks']
X = stock_data_df.drop(columns= col, axis = 1)

X.head()


Bullish  Neutral  Bearish  Bull 8 wk mov avg  Bull 16 wk mov avg  \
Date                                                                           
1987-11-06     0.47     0.31     0.22               0.46                0.29   
1987-11-13     0.31     0.41     0.28               0.43                0.28   
1987-11-20     0.39     0.42     0.19               0.41                0.28   
1987-11-27     0.27     0.46     0.27               0.39                0.30   
1987-12-04     0.25     0.33     0.42               0.36                0.30   

            Bear 8 wk mov avg  Bear 16 wk mov avg  Neutral 8 wk mov avg  \
Date                                                                      
1987-11-06               0.26                0.25                  0.28   
1987-11-13               0.28                0.26                  0.30   
1987-11-20               0.26                0.25                  0.33   
1987-11-27               0.26                0.25                  0.35   
1987-12-04               0.29                0.27                  0.35   

            Neutral 16 wk mov avg  Bull-Bear Spread   Close  
Date                                                         
1987-11-06                   0.29              0.25  250.41  
1987-11-13                   0.28              0.03  245.64  
1987-11-20                   0.28              0.20  242.00  
1987-11-27                   0.30              0.00  240.34  
1987-12-04                   0.30             -0.17  223.92

In [6]:
X.describe()


Bullish      Neutral      Bearish  Bull 8 wk mov avg  \
count  1704.000000  1704.000000  1704.000000        1704.000000   
mean      0.379231     0.315164     0.305657           0.379789   
std       0.100484     0.084425     0.095443           0.077578   
min       0.120000     0.080000     0.070000           0.180000   
25%       0.310000     0.250000     0.240000           0.320000   
50%       0.370000     0.320000     0.290000           0.380000   
75%       0.440000     0.370000     0.360000           0.430000   
max       0.750000     0.620000     0.700000           0.640000   

       Bull 16 wk mov avg  Bear 8 wk mov avg  Bear 16 wk mov avg  \
count         1704.000000        1704.000000         1704.000000   
mean             0.315258           0.305428            0.304853   
std              0.066789           0.073986            0.066769   
min              0.170000           0.150000            0.170000   
25%              0.270000           0.250000            0.260000   
50%              0.320000           0.290000            0.290000   
75%              0.360000           0.350000            0.340000   
max              0.500000           0.560000            0.540000   

       Neutral 8 wk mov avg  Neutral 16 wk mov avg  Bull-Bear Spread  \
count           1704.000000            1704.000000       1704.000000   
mean               0.315381               0.315258          0.073680   
std                0.070898               0.066789          0.176759   
min                0.160000               0.170000         -0.540000   
25%                0.260000               0.270000         -0.050000   
50%                0.320000               0.320000          0.080000   
75%                0.360000               0.360000          0.190000   
max                0.530000               0.500000          0.630000   

             Close  
count  1704.000000  
mean   1230.434941  
std     724.885964  
min     223.920000  
25%     616.237500  
50%    1164.320000  
75%    1473.377500  
max    3386.150000

In [7]:
X.shape

(1704, 11)

In [8]:
y.value_counts()

NEUTRAL    638
DOWN       637
UP         429
Name: Signal 4 wks, dtype: int64

In [9]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.33, random_state=42)
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=85)

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=85)

# Creating StandardScaler instance
scaler = StandardScaler()
#scaler=MinMaxScaler()

# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [10]:
# Resample the training data with the RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=500, random_state=78)
rf_model = rf_model.fit(X_train_scaled, y_train)
predictions = rf_model.predict(X_test_scaled)

In [11]:
# Calculated the balanced accuracy score
y_pred = rf_model.predict(X_test_scaled)
print(balanced_accuracy_score(y_test, predictions))
acc_score = accuracy_score(y_test, predictions)
print(acc_score)

0.4946248212151492
0.5117370892018779


In [12]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 1", "Actual 2", "Actual 3"], columns=["Predicted 1", "Predicted 2", "Predicted 3"]
)

In [13]:
# Print the imbalanced classification report
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 1  Predicted 2  Predicted 3
Actual 1           95           52           12
Actual 2           53           85           22
Actual 3           26           43           38

Accuracy Score : 0.5117370892018779
Classification Report
              precision    recall  f1-score   support

        DOWN       0.55      0.60      0.57       159
     NEUTRAL       0.47      0.53      0.50       160
          UP       0.53      0.36      0.42       107

    accuracy                           0.51       426
   macro avg       0.52      0.49      0.50       426
weighted avg       0.51      0.51      0.51       426



In [14]:
# List the features sorted in descending order by feature importance
importances = rf_model.feature_importances_
importances_sorted = sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)
importances_sorted


[(0.154220621447714, 'Close'),
 (0.09330395948431254, 'Bull 8 wk mov avg'),
 (0.09197373246957069, 'Bull-Bear Spread'),
 (0.09166591511535763, 'Bear 16 wk mov avg'),
 (0.09032279947737716, 'Bear 8 wk mov avg'),
 (0.0873270133414753, 'Neutral'),
 (0.08673017857113459, 'Bearish'),
 (0.08579059678357699, 'Neutral 8 wk mov avg'),
 (0.08416236152404202, 'Bullish'),
 (0.06770778622729018, 'Neutral 16 wk mov avg'),
 (0.06679503555814909, 'Bull 16 wk mov avg')]

In [15]:
# Train the Easy Ensemble Adaboost Classifier
from sklearn.ensemble import AdaBoostClassifier

ada_model = AdaBoostClassifier(n_estimators=500, random_state=78)
ada_model = ada_model.fit(X_train_scaled, y_train)
predictions = ada_model.predict(X_test_scaled)

In [16]:
# Calculated the balanced accuracy score
y_pred = ada_model.predict(X_test_scaled)
print(balanced_accuracy_score(y_test, predictions))

0.424750435941143


In [17]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[82, 45, 32],
       [52, 78, 30],
       [35, 43, 29]], dtype=int64)

In [18]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

       DOWN       0.49      0.52      0.67      0.50      0.59      0.34       159
    NEUTRAL       0.47      0.49      0.67      0.48      0.57      0.32       160
         UP       0.32      0.27      0.81      0.29      0.47      0.21       107

avg / total       0.44      0.44      0.71      0.44      0.55      0.30       426



In [22]:
#LSTM MODEL
# Using the bull-bear spread we attempt to predict prices
import hvplot.pandas

bull_bear_df = stock_data_df[["Bull-Bear Spread", 'Close', 'Close in 4 wks', 'Close in 8 wks']]
bull_bear_df.head()

Bull-Bear Spread   Close  Close in 4 wks  Close in 8 wks
Date                                                                
1987-11-06              0.25  250.41          223.92          247.08
1987-11-13              0.03  245.64          235.32          243.40
1987-11-20              0.20  242.00          249.16          252.05
1987-11-27              0.00  240.34          252.02          246.50
1987-12-04             -0.17  223.92          247.08          257.07

In [23]:
# This function accepts the column number for the features (X) and the target (y)
# It chunks the data up with a rolling window of Xt-n to predict Xt
# It returns a numpy array of X any y
def window_data(df, window, feature_col_number, target_col_number):
    X = []
    y = []
    for i in range(len(df) - window - 1):
        features = df.iloc[i:(i + window), feature_col_number]
        target = df.iloc[(i + window), target_col_number]
        X.append(features)
        y.append(target)
    return np.array(X), np.array(y).reshape(-1, 1)

In [39]:
# Predict Closing Prices using a 10 day window of previous closing prices
# Try a window size anywhere from 1 to 10 and see how the model performance changes
window_size = 14

# Column index 1 is the `Close` column
feature_column = 0
target_column = 2
X, y = window_data(bull_bear_df, window_size, feature_column, target_column)

In [40]:
# Use 70% of the data for training and the remainder for testing
split = int(0.7 * len(X))
X_train = X[: split - 1]
X_test = X[split:]
y_train = y[: split - 1]
y_test = y[split:]

In [41]:
# Use MinMaxScaler to scale the data between 0 and 1. 
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
scaler.fit(y)
y_train = scaler.transform(y_train)
y_test = scaler.transform(y_test)

In [42]:
# Reshape the features for the model
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))
print (f"X_train sample values:\n{X_train[:5]} \n")
print (f"X_test sample values:\n{X_test[:5]}")

X_train sample values:
[[[0.67521368]
  [0.48717949]
  [0.63247863]
  [0.46153846]
  [0.31623932]
  [0.38461538]
  [0.51282051]
  [0.52991453]
  [0.45299145]
  [0.58119658]
  [0.52991453]
  [0.37606838]
  [0.43589744]
  [0.60683761]]

 [[0.48717949]
  [0.63247863]
  [0.46153846]
  [0.31623932]
  [0.38461538]
  [0.51282051]
  [0.52991453]
  [0.45299145]
  [0.58119658]
  [0.52991453]
  [0.37606838]
  [0.43589744]
  [0.60683761]
  [0.54700855]]

 [[0.63247863]
  [0.46153846]
  [0.31623932]
  [0.38461538]
  [0.51282051]
  [0.52991453]
  [0.45299145]
  [0.58119658]
  [0.52991453]
  [0.37606838]
  [0.43589744]
  [0.60683761]
  [0.54700855]
  [0.48717949]]

 [[0.46153846]
  [0.31623932]
  [0.38461538]
  [0.51282051]
  [0.52991453]
  [0.45299145]
  [0.58119658]
  [0.52991453]
  [0.37606838]
  [0.43589744]
  [0.60683761]
  [0.54700855]
  [0.48717949]
  [0.55555556]]

 [[0.31623932]
  [0.38461538]
  [0.51282051]
  [0.52991453]
  [0.45299145]
  [0.58119658]
  [0.52991453]
  [0.37606838]
  [0.4358

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [43]:
# Build the LSTM model. 
# The return sequences need to be set to True if you are adding additional LSTM layers, but 
# You don't have to do this for the final layer. 

# Define the LSTM RNN model.
model = Sequential()

number_units =14
dropout_fraction = 0.2

# Layer 1
model.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_train.shape[1], 1))
    )
model.add(Dropout(dropout_fraction))

# Layer 2
model.add(LSTM(units=number_units, return_sequences=True))
model.add(Dropout(dropout_fraction))

# Layer 3
model.add(LSTM(units=number_units))
model.add(Dropout(dropout_fraction))

# Output layer
model.add(Dense(1))

In [44]:
# Compile the model
model.compile(optimizer="adam", loss="mean_squared_error")

In [45]:
# Summarize the model
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 14, 14)            896       
_________________________________________________________________
dropout_3 (Dropout)          (None, 14, 14)            0         
_________________________________________________________________
lstm_4 (LSTM)                (None, 14, 14)            1624      
_________________________________________________________________
dropout_4 (Dropout)          (None, 14, 14)            0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 14)                1624      
_________________________________________________________________
dropout_5 (Dropout)          (None, 14)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                

In [46]:
# Train the model
# Use at least 10 epochs
# Do not shuffle the data
# Experiement with the batch size, but a smaller batch size is recommended

model.fit(X_train, y_train, epochs=30, shuffle=False, batch_size=1, verbose=1)

Epoch 1/30
1181/1181 [==============================] - 14s 12ms/step - loss: 0.0010
Epoch 2/30
1181/1181 [==============================] - 14s 12ms/step - loss: 0.0011
Epoch 3/30
1181/1181 [==============================] - 14s 12ms/step - loss: 0.0013
Epoch 4/30
1181/1181 [==============================] - 15s 12ms/step - loss: 0.0015
Epoch 5/30
1181/1181 [==============================] - 14s 12ms/step - loss: 0.0017
Epoch 6/30
1181/1181 [==============================] - 14s 12ms/step - loss: 0.0018
Epoch 7/30
1181/1181 [==============================] - 14s 12ms/step - loss: 0.0018
Epoch 8/30
1181/1181 [==============================] - 14s 12ms/step - loss: 0.0020
Epoch 9/30
1181/1181 [==============================] - 14s 12ms/step - loss: 0.0021
Epoch 10/30
1181/1181 [==============================] - 14s 12ms/step - loss: 0.0020- ETA: 0s - lo
Epoch 11/30
1181/1181 [==============================] - 14s 12ms/step - loss: 0.0020
Epoch 12/30
1181/1181 [==========================

In [47]:
# Evaluate the model
model.evaluate(X_test, y_test)

16/16 [==============================] - 0s 5ms/step - loss: 0.1125


0.1125263050198555

In [48]:
# Make some predictions
predicted = model.predict(X_test)

In [49]:
# Recover the original prices instead of the scaled version
predicted_prices = scaler.inverse_transform(predicted)
real_prices = scaler.inverse_transform(y_test.reshape(-1, 1))

In [50]:
# Create a DataFrame of Real and Predicted values
stocks = pd.DataFrame({
    "Real": real_prices.ravel(),
    "Predicted": predicted_prices.ravel()
})
stocks.head()

Real    Predicted
0  1225.85  1117.929810
1  1223.25  1118.173828
2  1199.73  1118.251099
3  1206.07  1118.181763
4  1228.28  1118.128906

In [51]:
# Plot the real vs predicted values as a line chart
stocks.hvplot()

:NdOverlay   [Variable]
   :Curve   [index]   (value)